SET NAMES 'utf8mb4';

INSERT INTO pages (slug, title, type) VALUES ('resolution-problemes', 'Résolution de problèmes', 'competence');

-- Hero
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'header_title', 'h1', 'Résolution de problèmes', 'hero', 1);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'header_breadcrumb', 'label', 'home / compétences', 'hero', 2);

-- Définition
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'definition_title', 'h2', 'DÉFINITION', 'definition', 1);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'definition_p1', 'paragraph', 'La capacité à résoudre des problèmes de codage ou de conception complexe consiste, selon moi, à être capable d''anticiper, de questionner et de proposer des solutions à des bugs ou lors de crashs techniques tant redoutés qui génèrent autant de stress.', 'definition', 2);

-- Section 1 : Éléments de preuve
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_number', 'number', '1', 'preuves', 1);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_title', 'h2', 'éléments de preuve', 'preuves', 2);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_p1', 'paragraph', 'Devant développer plusieurs projets logiciels sous la directive de David, j''ai dû faire preuve de capacité de résolution de problèmes, tant dans les phases de conception que dans les phases de maintenance de code base, où parfois des régressions de code pouvaient impacter la santé de la code base.', 'preuves', 3);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_p2', 'paragraph', 'Dans les phases de conception, pour le projet de ColiBack Premium, il a fallu que j''innove pour imaginer un web service dialoguant avec les boutiques e-commerçantes Shopify parce que l''environnement Shopify est clos pour des raisons de sécurité et pour ses clients. Ainsi, trouver une solution devient créatif car il faut comprendre le fonctionnement des environnements techniques et imaginer la solution la plus simple à mettre en place pour maximiser la valeur de son action de développement en optimisant son temps.', 'preuves', 4);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_p3', 'paragraph', 'Dans le cas du projet MyCityStock, j''ai dû mettre en place une route d''authentification sur une base de données Firebase dans l''environnement Google. La grande complexité ne résidait pas dans le fait de se connecter en tant qu''utilisateur par le sign-in/up de la page mais de pouvoir créer un utilisateur connecté dynamiquement dont l''appel se ferait à partir du CMS headless Directus et dont la connexion a posteriori se ferait à partir de lui. Pour résoudre ce problème, j''ai lu de la documentation et cherché à comprendre comment le système d''authentification fonctionnait sur Firebase, les flows sur Directus et cherché à résoudre le souci de comment faire communiquer ces différentes briques logicielles.', 'preuves', 5);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_p4', 'paragraph', 'D''autre part, être en capacité de résoudre des problèmes se perçoit également dans les cas de bugs logiciels. Lorsque ColiBack Premium a été déployé, j''avais mis au point un logiciel peu résilient, chose que j''ai dû corriger par la suite pour rendre le code maintenable au vu de la densité de sa code base.', 'preuves', 6);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section1_p5', 'paragraph', 'Ainsi, il pouvait arriver au tout début du projet, alors que les environnements de développement n''avaient pas été configurés et que l''application était déployée, qu''il y ait des régressions de système. Ainsi, il fallait remonter tout le fil de la donnée pour comprendre à quel point le logiciel crashait, dans ce genre de situation extrêmement stressante il faut savoir faire preuve de sang-froid, d''esprit d''équipe et boire beaucoup de café et s''en servir de leçon pour coder en clean code par la suite.', 'preuves', 7);

-- Section 2 : Auto-évaluation
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section2_number', 'number', '2', 'evolution', 1);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section2_title', 'h2', 'auto-évaluation', 'evolution', 2);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section2_p1', 'paragraph', 'Avant d''intégrer ColiBack, j''aurais été convaincu que la capacité à résoudre des problèmes complexes se résumait à trouver une manière élégante et performante de programmer, mais dans le monde de l''entreprise, je me rends compte qu''être en capacité de bien coder est une nécessité mais que la capacité à résoudre des problèmes nécessite de prendre de la hauteur sur les systèmes développés et d''être en capacité de faire du pair-programming ou de vulgariser les stacks techniques pour trouver des solutions entre plusieurs développeurs.', 'evolution', 3);

-- Section 3 : Auto-critique
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section3_number', 'number', '3', 'autocritique', 1);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section3_title', 'h2', 'auto-critique', 'autocritique', 2);
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'section3_p1', 'paragraph', 'En tant qu''ingénieur logiciel débutant, j''ai conscience que j''ai souvent besoin de me référer aux conseils techniques de mon mentor, pour imaginer une solution plus optimisée et adaptée à l''environnement existant. Encore une chose qui me pousse à voir dans le métier d''ingénieur logiciel, un métier où le relationnel est une capacité fondamentale.', 'autocritique', 3);

-- Projets liés
INSERT INTO content_blocks (page_slug, block_key, type, value, category, order_index) VALUES ('resolution-problemes', 'projects_title', 'h2', 'projets', 'projets', 1);
