SET NAMES 'utf8mb4';

INSERT IGNORE INTO projects (slug, title, subtitle, description, category, order_index)
  VALUES ('coliback-premium', 'Coliback Premium', 'Plateforme de gestion des retours Shopify',
    'Alternance Ingénieur Logiciel — ColiBack. Développement d''une plateforme automatisant les retours et échanges pour boutiques Shopify.',
    'ingénierie logiciel', 1);

INSERT IGNORE INTO pages (slug, title, type)
  VALUES ('coliback-premium', 'Coliback Premium', 'projet');

-- ── hero ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','hero','header_title','h1','Coliback Premium',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','hero','header_breadcrumb','label','home / projets',2);

-- ── intro ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_p1','paragraph','Au cours de mon alternance réalisée dans le cadre du Master Ingénierie Logicielle de l''ISCOD, j''ai participé à la conception et au développement de ColiBack Premium, une plateforme numérique destinée à automatiser les procédures de retour et d''échange de produits pour les boutiques e-commerce utilisant Shopify.\n\nJ''ai intégré ColiBack en octobre 2024 au sein de l''équipe technique pilotée par David Dias, Directeur des Systèmes d''Information. Cette alternance m''a permis de découvrir un environnement où les enjeux logistiques et numériques sont étroitement liés. Historiquement spécialisée dans la gestion des retours colis, ColiBack a progressivement développé un ensemble de solutions logicielles permettant aux e-commerçants d''externaliser une partie de leurs processus logistiques.\n\nL''entreprise appartient au réseau national E-Logik et s''appuie notamment sur la solution E-Kan pour assurer le suivi des commandes, des stocks et des mouvements logistiques.\n\nDans ce contexte, l''objectif du projet était de concevoir une solution capable de s''intégrer naturellement à cet écosystème tout en répondant à une problématique croissante observée chez les clients : la gestion des retours et des échanges de produits issus des boutiques Shopify.\n\nAvant le développement de ColiBack Premium, les solutions existantes permettaient principalement de déclarer un retour produit. Les processus d''échange restaient largement manuels et nécessitaient l''intervention des équipes support ou logistiques. Cette situation générait des délais de traitement importants, une charge opérationnelle élevée ainsi qu''une expérience utilisateur parfois insatisfaisante pour les consommateurs finaux.\n\nLe projet visait donc à concevoir un véritable moteur métier capable d''automatiser l''ensemble du cycle de retour : identification des produits retournables, sélection de variantes alternatives disponibles, création des retours Shopify, génération des étiquettes transporteurs et création automatique des commandes d''échange.\n\nLes contraintes imposées par Shopify nécessitaient une maîtrise avancée des API GraphQL, des mécanismes OAuth, de la sécurisation des échanges de données ainsi que des problématiques d''architecture logicielle distribuée.\n\nCette réalisation m''a permis de développer plusieurs compétences fondamentales du Master Ingénierie Logicielle :',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_1','list_item','conception d''architectures logicielles orientées services ;',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_2','list_item','développement d''API sécurisées ;',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_3','list_item','intégration de systèmes tiers ;',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_4','list_item','gestion de projet Agile ;',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_5','list_item','pratiques DevOps et déploiement cloud ;',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_6','list_item','sécurité applicative et conformité RGPD ;',7);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','intro','intro_comp_7','list_item','travail collaboratif avec des équipes métiers et techniques.',8);

-- ── objectifs ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_title','h2','1. Objectifs du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_1_title','h3','1.1  Concevoir une solution informatique évolutive',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_1_text','paragraph','Le premier objectif consistait à développer une plateforme capable d''être déployée rapidement auprès de nouveaux clients tout en garantissant une forte capacité d''évolution.\nLa croissance continue de l''écosystème Shopify imposait de concevoir une architecture suffisamment flexible pour absorber les évolutions de l''API et les nouvelles attentes des e-commerçants sans nécessiter de refonte majeure.\n\nJ''ai donc participé à la conception d''une architecture modulaire respectant les principes SOLID afin de garantir la maintenabilité du logiciel sur le long terme.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_2_title','h3','1.2  Enrichir le système d''information de ColiBack',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_2_text','paragraph','Le second objectif consistait à faire évoluer l''offre numérique de ColiBack.\n\nL''entreprise disposait déjà d''outils permettant de suivre les flux logistiques, les commandes et les stocks. L''ajout de ColiBack Premium devait permettre de compléter cette chaîne numérique en automatisant la gestion des retours et des échanges directement depuis les boutiques Shopify.\n\nCette évolution représentait un avantage concurrentiel important puisqu''elle permettait à ColiBack de proposer un service complémentaire à forte valeur ajoutée tout en réduisant la charge opérationnelle des équipes logistiques.',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_3_title','h3','1.2  Mettre en pratique les compétences du Master',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','objectifs','ch1_3_text','paragraph','Ce projet représentait également l''occasion de mettre en œuvre les méthodes et technologies étudiées durant ma formation.\n\nJ''ai ainsi pu appliquer concrètement des notions d''architecture logicielle, de gestion de projet Agile, de développement d''API REST, d''intégration GraphQL, de conteneurisation Docker ainsi que de sécurisation des infrastructures cloud.',7);

-- ── contexte ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','contexte','ch2_title','h2','2. Contexte humain et technique',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','contexte','ch2_1_title','h3','2.1 Les acteurs du projet',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','contexte','ch2_1_text','paragraph','Le développement de ColiBack Premium a mobilisé plusieurs profils complémentaires.\nDavid Dias intervenait en qualité de commanditaire et de responsable technique. Son rôle consistait à définir les besoins métiers et les orientations stratégiques du projet.\n\nLes développeurs E-Logik conseillaient sur le plan technique et normatif afin de garantir la cohérence des flux logistiques sur la plateforme e-kan et la bonne compréhension des concepts Shopify.\nLes e-commerçants partenaires ont également joué un rôle important dans la validation fonctionnelle du produit grâce à leurs retours d''expérience.\n\nEnfin, plusieurs experts techniques sont intervenus ponctuellement pour apporter leur expertise sur les sujets liés à l''architecture logicielle, à la sécurité et au déploiement cloud.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','contexte','ch2_2_title','h3','2.2 Environnement technique',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','contexte','ch2_2_text','paragraph','Le projet repose sur une architecture moderne construite autour de NodeJS et ExpressJS.\nLe serveur applicatif agit comme une couche intermédiaire entre les boutiques Shopify et les différents services ColiBack.\n\nLes données techniques sont stockées dans une base MariaDB hébergée dans un conteneur Docker.\nL''infrastructure est déployée sur un serveur Ubuntu hébergé chez OVH et protégée par Nginx qui assure le rôle de reverse proxy ainsi que la terminaison TLS grâce aux certificats Let''s Encrypt.\n\nLe choix de NodeJS s''est imposé pour sa capacité à gérer efficacement un grand nombre de requêtes asynchrones vers l''API Shopify.\n\nL''utilisation de Docker permet quant à elle de standardiser les environnements de développement et de production tout en facilitant les opérations de maintenance.\n\nEnfin, GraphQL a été retenu comme technologie principale d''interfaçage avec Shopify puisque cette dernière remplace progressivement ses anciennes API REST.\n\nL''ensemble de cette architecture répond à un objectif de scalabilité, de sécurité et de maintenabilité permettant d''accompagner la croissance future du service.',5);

-- ── enjeux ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','enjeux','ch3_title','h2','3. Enjeux et risques du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','enjeux','ch3_1_title','h3','3.1 Enjeux du projet',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','enjeux','ch3_1_text','paragraph','Le projet Coliback Premium représentait un enjeu stratégique pour Coliback puisqu''il visait à enrichir l''offre de services numériques proposée aux e-commerçants partenaires. L''objectif était de proposer une solution moderne permettant aux clients finaux de gérer eux-mêmes leurs demandes de retour ou d''échange directement depuis une interface dédiée.\n\nLe premier enjeu concernait la satisfaction des clients e-commerçants. Jusqu''alors, certaines opérations liées aux retours et aux échanges nécessitaient des interventions manuelles ou l''utilisation de solutions tierces souvent coûteuses. Coliback Premium devait permettre d''automatiser ces traitements tout en offrant une expérience utilisateur fluide aux consommateurs.\n\nUn second enjeu était l''intégration durable avec l''écosystème Shopify. Le projet dépendant fortement des API Shopify, il était indispensable de concevoir une architecture suffisamment souple pour s''adapter aux évolutions régulières de la plateforme tout en respectant les bonnes pratiques imposées par sa documentation technique.\n\nL''évolutivité constituait également un enjeu majeur. La solution devait pouvoir accueillir progressivement de nouveaux clients sans nécessiter de refonte de l''architecture. Cette exigence a conduit à concevoir une architecture multi-boutiques reposant sur l''identification des différentes boutiques via un système de shopId et de tokens d''accès indépendants.\n\nLa sécurité représentait également un enjeu central. Le service manipulant des commandes, des informations de livraison et des accès aux boutiques Shopify, il était indispensable de protéger les échanges de données, de limiter les accès aux ressources sensibles et de respecter les principes du RGPD.\n\nEnfin, le projet devait être réalisé dans des délais compatibles avec les attentes de la Direction Technique et des premiers clients pilotes intéressés par la solution.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','enjeux','ch3_2_title','h3','3.2 Risques identifiés',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','enjeux','ch3_2_text','paragraph','Plusieurs risques ont été identifiés dès le lancement du projet.\nLe premier concernait la complexité technique liée à l''intégration avec Shopify. La plateforme impose ses propres mécanismes d''authentification, son modèle de données GraphQL ainsi que des règles métier spécifiques concernant les retours, les échanges et la gestion des commandes. Une mauvaise compréhension de ces mécanismes aurait pu compromettre le bon fonctionnement du projet.\n\nUn risque d''architecture existait également. Des choix techniques inadaptés au début du projet auraient pu conduire à une solution difficile à maintenir ou incapable d''évoluer avec les besoins futurs de Coliback.\nLa sécurité représentait un autre risque important. Une mauvaise gestion des tokens Shopify ou des accès aux API aurait pu exposer les données des boutiques partenaires ou compromettre l''intégrité du système d''information de Coliback.\n\nLe risque de performance devait également être pris en compte. Le service étant destiné à être utilisé simultanément par plusieurs boutiques et plusieurs utilisateurs, il était nécessaire de concevoir une architecture capable de supporter une montée en charge progressive.\n\nEnfin, un risque fonctionnel concernait la compréhension des besoins réels des utilisateurs. Une mauvaise analyse des attentes des e-commerçants ou des clients finaux aurait pu conduire au développement de fonctionnalités peu adaptées aux usages du terrain.',5);

-- ── realisation ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_title','h2','4. Étapes du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_title','h3','4.1 Étude du besoin et définition du projet',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_text','paragraph','Le projet a débuté par plusieurs échanges avec le Directeur Technique afin de comprendre les objectifs métier et les attentes de Coliback.\n\nCette phase a permis d''identifier les problématiques rencontrées par les e-commerçants dans la gestion des retours et des échanges, mais également les contraintes imposées par Shopify et par l''écosystème informatique déjà en place chez Coliback.\n\nL''analyse du besoin a conduit à définir les principales fonctionnalités attendues :',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item1','list_item','consultation des produits retournables ;',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item2','list_item','gestion des retours ;',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item3','list_item','gestion des échanges ;',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item4','list_item','génération des commandes d''échange ;',7);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item5','list_item','intégration des informations transporteurs ;',8);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_1_item6','list_item','compatibilité avec les boutiques Shopify.',9);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_title','h3','4.2 Veille technologique et rédaction du cahier des charges',10);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_text','paragraph','Une phase de veille a ensuite été menée afin d''étudier les technologies imposées par Shopify et d''identifier les solutions techniques adaptées au projet.\n\nCette étude a porté notamment sur :',11);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item1','list_item','l''API GraphQL Shopify ;',12);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item2','list_item','le fonctionnement des applications Shopify ;',13);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item3','list_item','les mécanismes OAuth ;',14);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item4','list_item','Docker ;',15);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item5','list_item','NodeJS ;',16);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item6','list_item','les architectures SaaS multi-boutiques.',17);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_text2','paragraph','Ces recherches ont permis de rédiger un cahier des charges définissant :',18);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item7','list_item','les utilisateurs cibles ;',19);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item8','list_item','les fonctionnalités ;',20);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item9','list_item','les contraintes techniques ;',21);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item10','list_item','l''architecture envisagée ;',22);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_2_item11','list_item','les exigences de sécurité.',23);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_title','h3','4.3 Conception et développement du MVP',24);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_text','paragraph','La première version du produit a été développée sous la forme d''un MVP (Minimum Viable Product).\nL''objectif était de valider rapidement les principaux workflows métier avant d''enrichir progressivement la solution.\n\nLes premières fonctionnalités développées ont été :',25);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_item1','list_item','récupération des commandes Shopify ;',26);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_item2','list_item','identification des produits retournables ;',27);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_item3','list_item','création des retours ;',28);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_item4','list_item','génération des commandes d''échange.',29);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_3_text2','paragraph','Cette phase a permis de valider la faisabilité technique du projet et de confronter les premiers développements aux besoins réels des utilisateurs.',30);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_title','h3','4.4 Mise en place d''une organisation Agile',31);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_text','paragraph','Afin d''assurer un suivi régulier du projet, les développements ont été organisés selon une approche Agile.\nLes fonctionnalités ont été découpées en tâches unitaires puis intégrées dans un backlog de développement.\n\nCette organisation a permis :',32);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_item1','list_item','de suivre l''avancement du projet ;',33);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_item2','list_item','d''intégrer progressivement les retours utilisateurs ;',34);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_item3','list_item','de prioriser les développements ;',35);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_4_item4','list_item','de limiter les risques liés à l''évolution des besoins.',36);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_title','h3','4.5 Conception de l''architecture logicielle',37);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_text','paragraph','Une attention particulière a été portée à la conception de l''architecture.\nLe projet a été construit autour d''une architecture orientée services (SOA) composée de plusieurs couches distinctes :',38);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_item1','list_item','Routes ;',39);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_item2','list_item','Controllers ;',40);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_item3','list_item','Models ;',41);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_item4','list_item','Snippets GraphQL.',42);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_5_text2','paragraph','Cette organisation permet de séparer les responsabilités et facilite la maintenance du logiciel.\nL''architecture a également été conçue pour respecter les principes SOLID et favoriser les évolutions futures de la plateforme.',43);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_title','h3','4.6 Développement des fonctionnalités et tests',44);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_text','paragraph','Les principales fonctionnalités métier ont ensuite été développées.\n\nLes trois routes principales du service ont été conçues afin de répondre aux besoins du workflow de retour :',45);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item1','list_item','récupération des produits retournables ;',46);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item2','list_item','recherche de variants compatibles ;',47);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item3','list_item','création des retours et des échanges.',48);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_text2','paragraph','Des tests ont été réalisés tout au long du développement afin de valider :',49);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item4','list_item','les retours simples ;',50);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item5','list_item','les échanges de produits ;',51);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item6','list_item','les commandes contenant plusieurs articles ;',52);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item7','list_item','les cas d''erreur ;',53);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_item8','list_item','les scénarios liés aux variations de stock.',54);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_6_text3','paragraph','Cette phase a permis d''améliorer la robustesse du service avant son déploiement.',55);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_title','h3','4.7 Déploiement de la solution dans le cloud',56);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_text','paragraph','Une fois les développements validés, l''application a été déployée sur une infrastructure cloud hébergée chez OVH.\n\nCette étape a nécessité l''acquisition de nouvelles compétences en administration système et en DevOps.\nL''infrastructure mise en place repose sur :',57);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_item1','list_item','Ubuntu ;',58);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_item2','list_item','Docker ;',59);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_item3','list_item','MariaDB ;',60);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_item4','list_item','Nginx ;',61);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_item5','list_item','Let''s Encrypt.',62);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_7_text2','paragraph','Cette architecture garantit une bonne isolation des services tout en facilitant les futures évolutions de la plateforme.',63);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_8_title','h3','4.8 Présentation de la solution aux utilisateurs',64);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_8_text','paragraph','Après sa mise en production, Coliback Premium a été présenté à différents partenaires et clients potentiels.\n\nLa solution a notamment été présentée lors d''événements liés à l''écosystème Shopify ainsi qu''aux partenaires de Coliback et E-Kan.\n\nCes démonstrations ont permis de recueillir des retours utilisateurs utiles pour les évolutions futures du produit.',65);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_title','h3','4.9 Maintenance corrective et évolutive',66);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_text','paragraph','Depuis sa mise en production, le projet fait l''objet d''une maintenance continue.\n\nLes actions réalisées concernent notamment :',67);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_item1','list_item','la correction d''anomalies ;',68);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_item2','list_item','l''amélioration des performances ;',69);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_item3','list_item','l''ajout de nouvelles fonctionnalités ;',70);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_item4','list_item','l''adaptation aux évolutions de l''API Shopify.',71);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','realisation','ch4_9_text2','paragraph','Cette phase constitue aujourd''hui une partie importante du cycle de vie du projet.',72);

-- ── methodologie ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','methodologie','ch5_title','h2','5. Méthodologie adoptée',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','methodologie','ch5_text','paragraph','Pour mener à bien le projet Coliback Premium, une méthodologie Agile a été privilégiée.\nCette approche était particulièrement adaptée au contexte du projet, les besoins pouvant évoluer au fur et à mesure des échanges avec les utilisateurs et de la découverte des contraintes techniques de Shopify.\n\nLe projet a été découpé en plusieurs phases successives permettant de livrer progressivement des fonctionnalités utilisables. Chaque étape faisait l''objet d''une validation avant le lancement de la suivante.\n\nLes fonctionnalités ont été organisées sous forme de backlog afin de faciliter leur priorisation et leur suivi. Cette organisation a permis d''adapter rapidement le développement aux retours des utilisateurs et aux nouvelles contraintes identifiées durant le projet.\n\nDes échanges réguliers avec le Directeur Technique et les différents acteurs du projet ont également permis d''assurer une bonne cohérence entre les besoins métier et les choix techniques réalisés.\n\nCette méthode de travail a favorisé l''amélioration continue de la solution tout au long de son développement.',2);

-- ── conclusion ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_title','h2','6. Fin du projet et perspectives d''avenir',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_intro','paragraph','Le développement de Coliback Premium a permis à Coliback de disposer d''une nouvelle solution capable d''automatiser la gestion des retours et des échanges pour les boutiques Shopify.\n\nAu-delà de la réalisation technique, ce projet a constitué pour moi une expérience particulièrement enrichissante puisqu''il s''agit du premier projet professionnel complet que j''ai eu l''occasion de concevoir, développer, déployer et maintenir dans un contexte réel d''entreprise.\n\nCette expérience m''a permis de mieux comprendre les différentes étapes du cycle de vie d''un projet logiciel, depuis l''analyse du besoin jusqu''à la mise en production et au suivi des utilisateurs.\n\nÀ l''avenir, plusieurs évolutions sont envisagées pour poursuivre le développement de la solution :',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item1','list_item','ajout de nouvelles fonctionnalités de personnalisation ;',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item2','list_item','amélioration du suivi des retours et des échanges ;',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item3','list_item','intégration de nouveaux transporteurs ;',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item4','list_item','extension du service à d''autres plateformes e-commerce ;',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item5','list_item','amélioration des mécanismes de supervision et de monitoring ;',7);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_item6','list_item','automatisation plus poussée des déploiements via des outils DevOps.',8);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','conclusion','ch6_text2','paragraph','Ces perspectives permettront à Coliback Premium de continuer à évoluer afin de répondre aux besoins croissants des e-commerçants tout en conservant une architecture robuste, maintenable et évolutive.',9);

-- ── projets ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium','projets','projects_title','h2','projets',1);
