SET NAMES 'utf8mb4';

INSERT IGNORE INTO projects (slug, title, subtitle, description, category, order_index)
  VALUES ('coliback-premium-devops', 'Coliback Premium DevOps', 'Industrialisation et déploiement Docker/CI-CD',
    'Pilotage de la phase DevOps de Coliback Premium : conteneurisation Docker, Infrastructure as Code et pipeline CI/CD avec Jenkins.',
    'devops', 2);

INSERT IGNORE INTO pages (slug, title, type)
  VALUES ('coliback-premium-devops', 'Coliback Premium DevOps', 'projet');

-- ── hero ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','hero','header_title','h1','Coliback Premium DevOps',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','hero','header_breadcrumb','label','home / projets',2);

-- ── intro ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','intro','intro_p1','paragraph','Dans le cadre de mon Master en Ingénierie Logicielle à l''ISCOD et de mon alternance chez Coliback, j''ai eu l''opportunité de piloter la phase d''industrialisation et de déploiement du projet Coliback Premium. Cette étape charnière m''a permis de faire le pont entre le développement logiciel pur et les pratiques DevOps, devenues incontournables dans le cycle de vie d''une application moderne.\n\nColiback Premium a pour vocation de devenir une solution SaaS distribuée auprès de multiples boutiques e-commerce (notamment via des intégrations Shopify). Il était donc impératif de concevoir une infrastructure résiliente, facilitant les déploiements, les tests et la maintenance. En parallèle des développements applicatifs (backend en NodeJS et frontend en Symfony 6), j''ai mené une réflexion globale sur la virtualisation des ressources et l''automatisation des processus techniques.\n\nCette mission a constitué un véritable tremplin : elle m''a permis de confronter les concepts d''architecture et de conteneurisation étudiés en Master à des impératifs de production réels, tout en développant une expertise pointue sur Docker et l''intégration continue (CI/CD).',1);

-- ── objectifs ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','objectifs','ch1_title','h2','1. Objectifs du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','objectifs','ch1_1_title','h3','1.1  Faciliter les déploiements et garantir la parité d''environnement via Docker',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','objectifs','ch1_1_text','paragraph','Le premier objectif était d''en finir avec le syndrome du "ça marche sur ma machine". L''application reposant sur une stack hétérogène (serveur NodeJS, base de données MariaDB, reverse proxy Nginx), il fallait simplifier drastiquement son installation.\n\nL''utilisation de Docker devait permettre d''encapsuler ces différents services dans des conteneurs isolés, reproductibles et facilement portables, garantissant ainsi une stricte parité de configuration entre les postes des développeurs et les serveurs de production.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','objectifs','ch1_2_title','h3','1.2  Industrialiser les workflows de développement',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','objectifs','ch1_2_text','paragraph','Le second objectif consistait à poser les fondations d''un travail d''équipe fluide et scalable.\n\nIl s''agissait de construire une chaîne d''intégration capable de tester automatiquement les modifications avant toute mise en production, de limiter les régressions et de fluidifier l''onboarding de nouveaux développeurs.\n\nCette démarche s''inscrivait directement dans la volonté stratégique de Coliback de structurer son pôle IT.',5);

-- ── contexte ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','contexte','ch2_title','h2','2. Contexte humain et technique',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','contexte','ch2_1_title','h3','2.1 Contexte humain',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','contexte','ch2_1_text','paragraph','Ce projet a nécessité une forte synergie technique. En tant que développeur web, j''ai été le moteur sur les phases de R&D, de conception et d''implémentation des environnements Docker.\n\nJ''ai travaillé sous la supervision du Directeur Technique (David Dias), qui validait les choix d''architecture. Pour assurer la qualité de mes livrables, j''ai également collaboré avec un développeur senior.\n\nCet encadrement m''a permis de valider mes hypothèses théoriques face aux réalités de l''administration système en entreprise.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','contexte','ch2_2_title','h3','2.2 Environnement technique',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','contexte','ch2_2_text','paragraph','La stack applicative de Coliback Premium était alors en plein développement : un backend robuste sous NodeJS / ExpressJS, un frontend moderne en PHP Symfony 6, le tout devant cohabiter avec le portail historique de l''entreprise.\n\nParallèlement, le service informatique était en phase de restructuration. Historiquement, les développements étaient réalisés par le CTO ou externalisés. Ma mission portait donc un double enjeu technique et organisationnel : internaliser la compétence DevOps et moderniser le socle technologique de l''entreprise.',5);

-- ── enjeux ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_title','h2','3. Enjeux et risques du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_1_title','h3','3.1 Enjeux du projet',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_1_text','paragraph','Scalabilité et Robustesse : Construire une infrastructure capable d''encaisser la croissance future du projet SaaS.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_1_item1','list_item','Fiabilité : Réduire les temps d''indisponibilité (downtime) et sécuriser les mises en production grâce aux environnements conteneurisés.',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_1_item2','list_item','Montée en compétence globale : Introduire la culture DevOps au sein de Coliback pour moderniser les pratiques de l''équipe.',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_1_item3','list_item','Application académique : Mettre en œuvre les concepts d''Infrastructure as Code (IaC) et d''automatisation vus durant mon Master en conditions réelles.',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_2_title','h3','3.2 Risques identifiés',7);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_2_item1','list_item','Le manque d''expérience initiale : Une mauvaise appréhension des concepts de virtualisation aurait pu mener à des choix d''architecture inadaptés ou non performants.',8);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_2_item2','list_item','Vulnérabilités de sécurité : Des conteneurs mal configurés (ports exposés, gestion des droits root) ou des pipelines de déploiement poreux représentaient un risque pour le SI.',9);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','enjeux','ch3_2_item3','list_item','Over-engineering (l''usine à gaz) : Le risque d''introduire des outils trop complexes qui, au lieu de simplifier la maintenance, l''auraient rendue opaque pour le reste de l''équipe.',10);

-- ── realisation ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_title','h2','4. Étapes du projet',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_1_title','h3','4.1 Preuve de concept (POC) sur serveur NodeJS',2);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_1_text','paragraph','La première étape a été exploratoire : installation du moteur Docker sur un serveur Linux dédié à NodeJS pour effectuer des tests de virtualisation et valider la faisabilité technique du projet.',3);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_2_title','h3','4.2 Phase de R&D et montée en compétences',4);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_2_text','paragraph','J''ai consolidé les enseignements théoriques de mon Master par une phase de documentation intensive (documentation officielle Docker, bonnes pratiques de l''industrie).\n\nJ''ai ainsi maîtrisé la gestion fine des réseaux isolés (bridge networks), la persistance des données via les volumes, et l''orchestration locale des microservices.',5);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_3_title','h3','4.3 Modélisation de l''architecture',6);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_3_text','paragraph','Avant d''écrire la moindre ligne de code d''infrastructure, j''ai cartographié le système : identification des composants (Nginx, Node, MariaDB, Symfony), de leurs dépendances, des ports à exposer et des variables d''environnement à sécuriser.',7);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_4_title','h3','4.4 Implémentation de l''Infrastructure as Code (IaC)',8);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_4_text','paragraph','J''ai rédigé les Dockerfiles pour chaque service afin de créer des images optimisées, et conçu le fichier docker-compose.yml pour orchestrer le lancement simultané et interconnecté de toute la stack Coliback Premium.',9);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_5_title','h3','4.5 Provisioning et Déploiement',10);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_5_text','paragraph','Une fois les configurations testées en local, j''ai utilisé ces conteneurs pour provisionner les serveurs d''hébergement, transformant une installation manuelle complexe en une simple commande d''exécution.',11);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_6_title','h3','4.6 Parité des environnements (Dev / Preprod / Prod)',12);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_6_text','paragraph','La conteneurisation m''a permis de cloner instantanément l''architecture pour créer des environnements de développement, de préproduction (staging) et de production strictement identiques, éliminant ainsi les bugs liés aux différences de versions logicielles.',13);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_7_title','h3','4.7 Intégration et Déploiement Continus (CI/CD) avec Jenkins',14);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','realisation','ch4_7_text','paragraph','Pour automatiser le cycle de vie du code, j''ai configuré une pipeline d''intégration continue via Jenkins.\nCe workflow permet de déclencher automatiquement des tests à chaque commit et de fluidifier la livraison des nouvelles versions.\n\nCette étape a été décisive pour ma compréhension des enjeux collaboratifs du DevOps.',15);

-- ── methodologie ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','methodologie','ch5_title','h2','5. Méthodologie adoptée',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','methodologie','ch5_text','paragraph','Le pilotage de ce projet s''est fait en méthode Agile, couplée à une approche empirique Test-and-Learn.\n\nFace à une stack technologique nouvelle pour moi, chaque jalon était divisé en itérations courtes : apprentissage théorique, expérimentation sur un environnement bac-à-sable (sandbox), validation par le CTO, puis intégration sur l''infrastructure du projet.\n\nLes ressources académiques de l''ISCOD et l''encadrement des experts de Coliback ont été le socle de cette méthodologie itérative.',2);

-- ── conclusion ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','conclusion','ch6_title','h2','6. Conclusion et perspectives',1);
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','conclusion','ch6_text','paragraph','Ce projet marque une étape fondamentale dans mon parcours d''Ingénieur Logiciel : il m''a permis d''assimiler les pratiques DevOps non plus comme de simples concepts, mais comme de véritables garants de la qualité logicielle.\n\nAu-delà de la maîtrise technique de Docker ou de Jenkins, j''ai développé une vision systémique des applications modernes : j''ai compris comment la reproductibilité des environnements et l''automatisation des pipelines garantissent la maintenabilité d''un projet sur le long terme.\n\nLe bilan pour Coliback est très positif : les compétences acquises ont pu être réutilisées sur d''autres projets internes, participant activement à la modernisation du SI. L''infrastructure de Coliback Premium est aujourd''hui robuste, sécurisée et prête à évoluer.\n\nPersonnellement, cette réussite constitue une base solide sur laquelle je compte m''appuyer pour approfondir mes compétences en ingénierie Cloud, en architectures distribuées et en orchestration logicielle (Kubernetes).',2);

-- ── projets ──
INSERT INTO content_blocks (page_slug,category,block_key,type,value,order_index) VALUES ('coliback-premium-devops','projets','projects_title','h2','projets',1);
